server:
  port: 8081
#应用名称（nacos会将该名称当成服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 118.25.151.78:8848
      # 这些即使不配也有默认值
      discovery:
        username: nacos
        password: nacos
        namespace: public
